name: oncopower
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-242.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data
  intl: ^0.17.0
 
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  dartz: ^0.10.1
  rxdart: ^0.27.3
  fluttertoast: ^8.0.9
  custom_pop_up_menu: ^1.2.3+1
  responsive_builder: ^0.4.2
  beamer: ^1.4.0+1 
  focus_detector: ^2.0.1
  loading_animation_widget: ^1.1.0+3
  google_fonts: ^3.0.1
  package_info_plus: ^1.4.0
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0
  
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
  assets:
      - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true